# Generated by Django 5.2.17 on 2026-09-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="technology",
            name="slug",
            field=models.SlugField(blank=True, max_length=280, unique=True),
        ),
    ]
