# Generated by Django 5.2.17 on 2026-09-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_alter_technology_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technology",
            name="slug",
            field=models.SlugField(blank=True, max_length=280, null=True),
        ),
    ]
