# Generated by Django 5.2.17 on 2026-09-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_alter_technology_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technology",
            name="slug",
            field=models.SlugField(blank=True, default=1, max_length=280, unique=True),
            preserve_default=False,
        ),
    ]
