# Generated by Django 5.2.17 on 2026-09-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_alter_technology_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, max_length=280),
        ),
    ]
