# Generated by Django 5.2.17 on 2026-09-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, max_length=280, unique=True),
        ),
    ]
