# Generated by Django 5.2.17 on 2026-09-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="اگر فعال باشد، این پست در بخش «ویژه» بالای صفحهٔ بلاگ به\u200cصورت بزرگ نمایش داده می\u200cشود.",
                verbose_name="پست ویژه (نمایش بزرگ)",
            ),
        ),
    ]
