# Generated by Django 5.2.17 on 2026-09-13 06:37

import blog.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content_html",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=blog.utils.post_content_image_path),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_images",
                        to="blog.post",
                    ),
                ),
            ],
        ),
    ]
