# Generated by Django 5.2.17 on 2026-09-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="postimage",
            name="caption",
            field=models.CharField(blank=True, max_length=255, verbose_name="کپشن"),
        ),
    ]
