# Generated by Django 5.2.17 on 2026-09-13 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_postimage_caption"),
    ]

    operations = [
        migrations.AddField(
            model_name="postimage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=256)),
                ("answer", models.TextField()),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="blog.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "سوال متداول",
                "verbose_name_plural": "سوالات متداول",
                "ordering": ["order", "id"],
            },
        ),
    ]
