# Generated by Django 5.2.17 on 2026-09-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0002_experience_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="degree",
            field=models.CharField(
                choices=[("b", "کارشناسی"), ("m", "دکتری"), ("p", "کارشناسی ارشد")],
                max_length=1,
            ),
        ),
    ]
